apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cs-agent
  name: agent-controller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "delete", "get", "watch", "list"]