apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hosted-agent
  namespace: cs-agent
subjects:
- kind: ServiceAccount
  name: hosted-agent
  namespace: cs-agent
roleRef:
  kind: Role 
  name: hosted-agent
  apiGroup: rbac.authorization.k8s.io