jobs:
  testing:
    displayname: test deployment
    working-directory: ./main
    steps:
      - command: AgentDownloadArtifacts
        displayname: Download Artifacts
        with:
          url: https://anmockartifacts.blob.core.windows.net/release/main.zip
      - command: AzPowerShellCore
        working-directory: ./main
        displayname: deploy 1st ARM Template
        with:
          arguments: -ResourceGroupName CLOUD-SHIPPER-RG -StorageAccountName anmocktst
          scriptToRun: ./deploy-arm-template.ps1
          subscription: SUBSCRIPTION
          tenant: TENANT
          serviceprincipal: SERVICEPRINCIPAL_NAME
          secret: SERVICEPRINCIPAL_SECRET
      - command: AzPowerShellCore
        working-directory: ./main
        displayname: deploy 2nd ARM Template
        with:
          arguments: -ResourceGroupName CLOUD-SHIPPER-RG -StorageAccountName anmockshp
          scriptToRun: ./deploy-arm-template.ps1
          subscription: SUBSCRIPTION
          tenant: TENANT
          serviceprincipal: SERVICEPRINCIPAL_NAME
          secret: SERVICEPRINCIPAL_SECRET